### ISSUE TITLE
01 Submission Checklist

### ISSUE THREAD

**Issue by jtoledom1** [yisus28k/Single-Page_CV_ROADMAP.SH_exercice_1#1]
- [ ] Semantically correct HTML structure.
- [x] Single-page layout with sections for education, skills, and career history.
- [x] SEO meta tags in the head section.
- [ ] OG tags for better social media sharing.
- [x] A favicon linked in the head section.
